// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package vfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreateEvent-1]
	_ = x[ModifyEvent-2]
	_ = x[RemoveEvent-4]
	_ = x[RenameEvent-8]
	_ = x[AttributeEvent-16]
	_ = x[ErrorEvent-32]
}

const (
	_EventType_name_0 = "CreateEventModifyEvent"
	_EventType_name_1 = "RemoveEvent"
	_EventType_name_2 = "RenameEvent"
	_EventType_name_3 = "AttributeEvent"
	_EventType_name_4 = "ErrorEvent"
)

var (
	_EventType_index_0 = [...]uint8{0, 11, 22}
)

func (i EventType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case i == 4:
		return _EventType_name_1
	case i == 8:
		return _EventType_name_2
	case i == 16:
		return _EventType_name_3
	case i == 32:
		return _EventType_name_4
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
